### ISSUE TITLE
Consolidate README files for automate scripts into one location

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#72]
PR #53 brought automate scripts with methods available to perform networking capabilities for Openstack provider. There is now a dedicated folder under the root of the manageiq-cli project (Automate-Datastore) which contains all the files and a [README.md](https://github.com/rhpit/manageiq-cli/blob/master/Automate-Datastore/README.md). It also added a [AUTOMATE-DATASTORE.rst](https://github.com/rhpit/manageiq-cli/blob/master/AUTOMATE_DATASTORE.rst) at the root of the project explaining how to use the automate scripts.

I think it would be best if we could combine these two files or move AUTOMATE-DATASTORE.rst to the Automate-Datastore folder. This way everything related to automate scripts is in one location. What does everyone think?

**Comment by tehsmyers** [comment]
+1; unless miq itself has special handling of AUTOMATE-DATASTORE.rst (which is doubtful given that it's rst not md), consolidating into Automate-Datastore/README.md makes sense. (Edit: Or consolidate into the README into the root-level doc, either way is more useful than having two obvious places for datstore docs)

I was pondering the notion of including that readme in the docs, which is a little tricky because it's markdown, but here's a little PoC I whipped up. First, install [recommonmark](https://github.com/rtfd/recommonmark), then make the docs use it so they're able to read markdown, then link the readme into the docs:

```diff
diff --git a/doc/source/conf.py b/doc/source/conf.py
index 12d7062..da0932e 100644
--- a/doc/source/conf.py
+++ b/doc/source/conf.py
@@ -22,6 +22,8 @@
 # sys.path.insert(0, os.path.abspath('.'))
 import pkg_resources
 
+from recommonmark.parser import CommonMarkParser
+
 
 # -- General configuration ------------------------------------------------
 
@@ -44,8 +46,9 @@ templates_path = ['templates']
 # The suffix(es) of source filenames.
 # You can specify multiple suffix as a list of string:
 #
-# source_suffix = ['.rst', '.md']
-source_suffix = '.rst'
+source_parsers = {'.md': CommonMarkParser}
+source_suffix = ['.rst', '.md']
+# source_suffix = '.rst'
 
 # The master toctree document.
 master_doc = 'index'
diff --git a/doc/source/index.rst b/doc/source/index.rst
index 76e8939..bee7974 100644
--- a/doc/source/index.rst
+++ b/doc/source/index.rst
@@ -15,6 +15,7 @@ Welcome to manageiq-cli's documentation!
    quickstart
    cli/commands
    api
+   automate



```

`ln -s ../../Automate-Datastore/README.md doc/source/automate.md`

After rebuilding the docs, the "automate" link in the index toctree renders the contents of the automate datastore readme.

I haven't put any real thought into this, but my instinct says this is probably a bad idea. Regardless, I thought it was worth a mention.

**Comment by ryankwilliams** [comment]
@seandst I just consolidated the AUTOMATE-DATASTORE.rst and Automate-Datastore/README.md into one file Automate-Datastore/README.rst. I switched to restructured text to stay inline with the rest of our projects documentation. I also just tested importing my forked project with a README.rst within Automate-Datastore directory and no problems. If this is okay, I will open a PR shortly.
